apiVersion: apps/v1
kind: Deployment
metadata:
    name: wallet-api
spec:
    selector:
        matchLabels:
            app: wallet-api
    replicas: 1
    template:
        metadata:
            labels:
                app: wallet-api
        spec:
            containers:
                - name: wallet-api
                  imagePullPolicy: IfNotPresent
                  image: playtikatraining.jfrog.io/default-docker-local/local/python-wappet-api:latest
                  imagePullSecrets:
                  - name: regcred
                  resources:
                      limits:
                          cpu: 50m
                          memory: 100Mi
                      requests:
                          cpu: 25m
                          memory: 10Mi
                  ports:
                      - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
    name: wallet-api
spec:
    type: NodePort
    selector:
        app: example
    ports:
        - port: 5080
          targetPort: 5080
